SERVER_IP: 127.0.0.1
# 是否启用任务
enableJob: true
server:
  port: 8027
  servlet:
    context-path: /StockApi
# 引入 数据库的相关配置
spring:
  profiles:
    active:
      - dev
      - db
      - message
      - url
      - config